'use client';
import { useState } from 'react';
import { ArrowRight, CalendarDays, Check, Clock3, HeartPulse, MapPin, Menu, MessageCircle, ShieldCheck, Star, Stethoscope, X } from 'lucide-react';

const doctors = [{ initials:'SD', name:'Dr. Selin Demir', specialty:'Dermatoloji', detail:'Cilt sağlığı ve medikal estetik', color:'peach' }, { initials:'AY', name:'Dr. Ali Yılmaz', specialty:'Diş Hekimi', detail:'Ağız, diş ve çene sağlığı', color:'blue' }, { initials:'EK', name:'Uzm. Ece Kaya', specialty:'Psikoloji', detail:'Yetişkin ve çift terapisi', color:'lilac' }];

export default function Home() { const [menu,setMenu]=useState(false); const [sent,setSent]=useState(false); const [name,setName]=useState(''); const [phone,setPhone]=useState('');
 return <main><div className="announcement">Yeni danışanlarımıza özel · İlk görüşmede %15 avantaj</div><nav><a className="brand" href="#top"><span><HeartPulse size={18}/></span>nora<strong>klinik</strong></a><div className={menu?'links open':'links'}><a href="#services">Hizmetler</a><a href="#doctors">Doktorlarımız</a><a href="#why">Neden Nora?</a><a href="#contact">İletişim</a></div><a className="navbutton" href="#booking">Randevu al <ArrowRight size={15}/></a><button className="menubutton" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></nav>
 <section className="hero shell" id="top"><div><div className="eyebrow"><i/> İstanbul’un sevilen kliniği</div><h1>İyi hissetmek,<br/><em>iyi bir başlangıçla</em> başlar.</h1><p>Size ve sevdiklerinize bütünsel, güvenilir ve insana dokunan sağlık deneyimi sunuyoruz.</p><div className="actions"><a className="button" href="#booking">Randevu oluştur <ArrowRight size={17}/></a><a className="textlink" href="#services">Hizmetlerimizi keşfet <ArrowRight size={16}/></a></div><div className="rating"><b>4.9 <Star size={13} fill="currentColor"/></b><span>Google’da 240+ değerlendirme</span></div></div><div className="heroart"><div className="orb"/><div className="appointment-card"><small><CalendarDays size={16}/> Bir sonraki adım</small><h3>Bugün kendin için<br/>bir şey yap.</h3><div className="mini"><b>SD</b><span><strong>Dr. Selin Demir</strong><small>Dermatoloji · 14:30</small></span><Check size={17}/></div></div><div className="float"><ShieldCheck size={18}/><span><strong>Güvenli iletişim</strong><small>KVKK uyumlu</small></span></div></div></section>
 <div className="marquee">• Sağlığınıza iyi bakın　 • Size iyi gelen yer　 • Yanınızdayız　 • Sağlığınıza iyi bakın</div>
 <section className="shell section" id="services"><div className="heading"><div><div className="eyebrow">Nora’da her şey sizin için</div><h2>Sağlık yolculuğunuzda<br/><em>yanınızdayız.</em></h2></div><p>İhtiyacınız olan uzmanlığı, kolayca ulaşabileceğiniz bir deneyimle bir araya getiriyoruz.</p></div><div className="cards"><article className="service featured"><Stethoscope/><small>01</small><h3>Uzman doktorlar</h3><p>Alanında deneyimli hekimlerimizle kişiye özel sağlık planı.</p><a href="#doctors">Doktorlarımızı tanıyın <ArrowRight size={15}/></a></article><article className="service"><Clock3/><small>02</small><h3>Kolay randevu</h3><p>Size uygun zamanı seçin, onayınızı SMS veya WhatsApp’tan alın.</p><a href="#booking">Randevu oluşturun <ArrowRight size={15}/></a></article><article className="service"><HeartPulse/><small>03</small><h3>Bütünsel yaklaşım</h3><p>Sizi yalnızca şikâyetinizle değil, bütün hikâyenizle dinliyoruz.</p><a href="#why">Yaklaşımımızı keşfedin <ArrowRight size={15}/></a></article></div></section>
 <section className="section muted" id="doctors"><div className="shell"><div className="heading"><div><div className="eyebrow">Tanışalım</div><h2>Size iyi gelecek<br/><em>uzmanınız burada.</em></h2></div><a className="outline" href="#booking">Tüm doktorları gör <ArrowRight size={15}/></a></div><div className="doctors">{doctors.map(d=><article className="doctor" key={d.name}><div className={'portrait '+d.color}><b>{d.initials}</b><span><i/> Uygun</span></div><div><small>{d.specialty}</small><h3>{d.name}</h3><p>{d.detail}</p><a href="#booking">Profilini incele <ArrowRight size={14}/></a></div></article>)}</div></div></section>
 <section className="shell why" id="why"><div className="quote"><div>“Kendimi ilk kez<br/><em>gerçekten dinlenmiş</em><br/>hissettim.”</div><small>— Nora danışanı</small><span><ShieldCheck size={19}/> Güvenli alan<br/><b>Her zaman.</b></span></div><div><div className="eyebrow">Neden Nora?</div><h2>Çünkü sağlık,<br/><em>güvenle başlar.</em></h2><p>İlk mesajınızdan kontrolünüze kadar her adımda size alan açıyoruz. Şeffaf, anlaşılır ve insan odaklı bir klinik deneyimi için buradayız.</p><ul><li><Check/> Aynı gün içinde geri dönüş</li><li><Check/> Şeffaf fiyatlandırma</li><li><Check/> KVKK uyumlu veri güvenliği</li></ul></div></section>
 <section className="booking" id="booking"><div className="shell bookinggrid"><div><div className="eyebrow">İlk adımı birlikte atalım</div><h2>İyi hissetmeye<br/><em>bugün başlayın.</em></h2><p>Formu doldurun, ekibimiz en kısa sürede size ulaşsın.</p><div className="contact"><MessageCircle size={19}/> WhatsApp’tan yazın<br/><b>+90 212 555 20 20</b></div></div><div className="form">{sent?<div className="success"><Check/><h3>Talebiniz alındı.</h3><p>Ekibimiz en kısa sürede sizinle iletişime geçecek.</p><button className="button" onClick={()=>setSent(false)}>Yeni talep oluştur</button></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="formhead"><h3>Randevu talebi</h3><small><ShieldCheck size={14}/> Bilgileriniz güvende</small></div><label>Ad soyad<input required placeholder="Adınız ve soyadınız" value={name} onChange={e=>setName(e.target.value)}/></label><label>Telefon numarası<input required placeholder="05__ ___ __ __" value={phone} onChange={e=>setPhone(e.target.value)}/></label><div className="twocol"><label>Branş<select><option>Genel Muayene</option><option>Dermatoloji</option><option>Diş Hekimliği</option><option>Psikoloji</option></select></label><label>Tarih<input type="date"/></label></div><label className="consent"><input type="checkbox" required/> KVKK aydınlatma metnini okudum.</label><button className="button full">Randevu talebi gönder <ArrowRight size={16}/></button></form>}</div></div></section>
 <footer className="shell footer" id="contact"><a className="brand"><span><HeartPulse size={18}/></span>nora<strong>klinik</strong></a><div><MapPin size={14}/> Teşvikiye, İstanbul · <Clock3 size={14}/> Pzt–Cmt 09:00–19:00</div><small>© 2024 Nora Klinik</small></footer></main> }
